# Generated by Django 5.0.6 on 2024-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_alter_revrubric_options_alter_rubric_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытое'),
        ),
    ]
